CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(500),
    DATE_OF_BIRTH DATE,
    PASSWORD VARCHAR(500) NOT NULL
);
CREATE TABLE PHONE_DATA (
    ID SERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    PHONE VARCHAR(13) NOT NULL UNIQUE,
    CONSTRAINT fk_user FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
CREATE TABLE EMAIL_DATA (
    ID SERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    EMAIL VARCHAR(200) UNIQUE,
    CONSTRAINT fk_user_email FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
CREATE TABLE ACCOUNT (
    ID SERIAL PRIMARY KEY,
    USER_ID BIGINT NOT NULL UNIQUE,
    BALANCE NUMERIC CHECK (BALANCE >= 0),
    CONSTRAINT fk_user_account FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

INSERT INTO USERS (NAME, DATE_OF_BIRTH, PASSWORD) VALUES
('Alice', '1990-01-15', 'password123'),
('Bob', '1985-06-30', 'securepass'),
('Charlie', '2000-12-01', 'mypassword');

INSERT INTO PHONE_DATA (USER_ID, PHONE) VALUES
(1, '79001112233'),
(1, '79001112234'),
(2, '79001112235'),
(3, '79001112236');

INSERT INTO EMAIL_DATA (USER_ID, EMAIL) VALUES
(1, 'alice@example.com'),
(2, 'bob@example.com'),
(3, 'charlie@example.com'),
(3, 'charlie2@example.com');

INSERT INTO ACCOUNT (USER_ID, BALANCE) VALUES
(1, 1000.00),
(2, 500.50),
(3, 0.00);

